default: &default
  adapter: sqlite3
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # timeout: 5000
  # encoding: utf8
  database: tereza_abx_picker

  username: tereza
  password: ajhxx6xGzYdlh0N6
  host: dokku-hosted.thruhere.net
  port: 8332


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
